
import { GoogleGenAI, Type } from "@google/genai";

/**
 * Transcribes audio and generates a summary using the Gemini model.
 * The API key is sourced from the environment variable process.env.API_KEY.
 */
export const transcribeAndSummarize = async (audioBase64: string, mimeType: string) => {
  // Access key directly from process.env as per instructions. 
  // If undefined, the SDK throws the error the user saw.
  const apiKey = process.env.API_KEY;
  
  if (!apiKey) {
    throw new Error("System API Key is missing. Please ensure your environment is configured correctly.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: [
        {
          parts: [
            {
              inlineData: {
                mimeType: mimeType,
                data: audioBase64,
              },
            },
            {
              text: "Act as an expert meeting scribe. Please provide a verbatim transcription followed by a highly structured summary including: # Executive Summary, ## Key Discussion Points, ## Decisions Made, and ### Action Items (with owners if mentioned). Use Markdown for formatting.",
            },
          ],
        },
      ],
    });

    if (!response.text) {
      throw new Error("No text was generated by the AI. The recording might be silent or too short.");
    }

    return response.text;
  } catch (error: any) {
    console.error("Gemini AI error:", error);
    // Provide specific guidance for the common "API key" error message
    if (error.message?.includes('API_KEY_INVALID')) {
      throw new Error("The configured API key is invalid.");
    }
    throw new Error(error.message || "An error occurred while communicating with BobbyAi services.");
  }
};
